
services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
    - .env
    networks :
    - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:ben10
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:ben10
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception


volumes:
  mariadb:
   driver: local
   driver_opts:
      device: $HOME/data/mariadb
      type : none
      o : bind

  wordpress:
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      type : none
      o : bind

networks:
  inception:
   name: inception