version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_network
    secrets:
      - db_password
      - db_root_password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    depends_on:
      - mariadb
    networks:
      - inception_network
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - inception_network
    secrets:
      - db_password
      - db_root_password

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../data/wordpress
      o: bind
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../data/database
      o: bind

networks:
  inception_network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt