
services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
    - .env
    networks :
    - inception
    restart: always

  nginx:
    image: nginx:ben10
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:ben10
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always


volumes:
  mariadb:
   driver: local
   driver_opts:
      device: $HOME/data/mariadb
      type : none
      o : bind

  wordpress:
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      type : none
      o : bind

networks:
  inception:
   name: inception